applicationInfo:
    environmentId: production

server:
    port: 8080
    use-forward-headers: true

spring:
    h2:
        console:
            enabled: false
logging:
    file: application-debug.log

