across:
    development:
        active: true

acrossHibernate:
    hibernate-properties:
        hibernate.format_sql: false
        hibernate.use_sql_comments: false
        hibernate.show_sql: false

applicationInfo:
    environmentId: development

server:
    error:
        includeStacktrace: ALWAYS
    port: 8080

spring:
    datasource:
        url: "jdbc:h2:./local-data/db/lamis-db"
        username: sa
